version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 13.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - homebrew-v1-
      - run:
          name: Install Homebrew packages
          command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew tap homebrew/cask-versions
            brew install visual-studio jq
      - save_cache:
          key: homebrew-v1-default
          paths:
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew
      - run:
          name: Install Visual Studio for Mac
          command: ./.circleci/install-vs-mac.sh
      - run:
          name: Restore NuGet dependencies
          command: msbuild -t:Restore scratch-link-mac/scratch-link-mac.csproj
      - run:
          name: Build for Mac
          command: |
            "/Applications/Visual Studio.app/Contents/MacOS/vstool" build -t:Build -c:Release "${PWD}/scratch-link.sln"
      - run:
          name: Zip the app
          command: |
            mkdir -p Artifacts
            cd scratch-link/bin/Debug/net6.0-maccatalyst/*/*.app/..
            ditto -v -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 \
              scratch-link.app ../../../../../Artifacts/scratch-link-mac.zip
      - store_artifacts:
          path: Artifacts/
workflows:
  version: 2
  build:
    jobs:
      - build-mac
