version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 13.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - visual-studio-mac-v3
      - run:
          name: Install/Extract Visual Studio for Mac
          command: |
            # CACHE_ARCHIVE must match the path in save_cache
            CACHE_ARCHIVE="/tmp/visual-studio-mac-v3.tar.gz"
            export HOMEBREW_NO_AUTO_UPDATE=1 # for speed
            bash ./.circleci/install-or-extract-vs-mac.sh "$CACHE_ARCHIVE"
      - save_cache:
          key: visual-studio-mac-v3
          paths: # Caching an archive instead of loose files works around CircleCI's issues with extracting links and permissions on macOS
            - /tmp/visual-studio-mac-v3.tar.gz
      - run:
          name: Restore NuGet dependencies
          command: msbuild -t:Restore -p:Configuration=Release scratch-link.sln
      - run:
          name: Build for Mac
          command: |
            "/Applications/Visual Studio.app/Contents/MacOS/vstool" build -t:Build -c:Release "${PWD}/scratch-link.sln"
            mkdir -p Artifacts
            cp -v scratch-link-mac/bin/Release/"Scratch Link"-*.pkg Artifacts/
      - run:
          name: Zip the bare app
          command: |
            mkdir -p Artifacts
            cd scratch-link-mac/bin/Release/
            ditto -v -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 \
              "Scratch Link.app" ../../../Artifacts/scratch-link-mac.zip
      - store_artifacts:
          path: Artifacts/
workflows:
  version: 2
  build:
    jobs:
      - build-mac
