version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 13.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - visual-studio-mac-v3
      - run:
          name: Install/Extract Visual Studio for Mac
          command: |
            # CACHE_ARCHIVE must match the path in save_cache
            CACHE_ARCHIVE="/tmp/visual-studio-mac-v3.tar.gz"
            if [ -f "$CACHE_ARCHIVE" ]; then
              echo "Cache found. Extracting..."
              sudo tar -x -C / -P -p --mac-metadata --totals -v -f "$CACHE_ARCHIVE"
            else
              echo "Cache not found. Installing..."
              export HOMEBREW_NO_AUTO_UPDATE=1
              brew tap homebrew/cask-versions
              brew install visual-studio jq
              ./.circleci/install-vs-mac.sh
              echo "Caching for next time..."
              sudo tar -c -a -C / -P -p --mac-metadata --totals -v -f "$CACHE_ARCHIVE" \
                "/Applications/Visual Studio.app" \
                "/Applications/Xamarin Profiler.app" \
                "/Library/Frameworks/Mono.framework" \
                "/Library/Frameworks/Xamarin.Mac.framework" \
                "/usr/local/share/dotnet" \
                "/etc/paths.d/dotnet" \
                "/etc/paths.d/dotnet-cli-tools" \
                "/etc/paths.d/mono-commands"
            fi
      - save_cache:
          key: visual-studio-mac-v3
          paths: # Caching an archive instead of loose files works around CircleCI's issues with extracting links and permissions on macOS
            - /tmp/visual-studio-mac-v3.tar.gz
      - run:
          name: Restore NuGet dependencies
          command: msbuild -t:Restore -p:Configuration=Release scratch-link.sln
      - run:
          name: Build for Mac
          command: |
            "/Applications/Visual Studio.app/Contents/MacOS/vstool" build -t:Build -c:Release "${PWD}/scratch-link.sln"
      - run:
          name: Zip the app
          command: |
            mkdir -p Artifacts
            cd scratch-link/bin/Debug/net6.0-maccatalyst/*/*.app/..
            ditto -v -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 \
              scratch-link.app ../../../../../Artifacts/scratch-link-mac.zip
      - store_artifacts:
          path: Artifacts/
workflows:
  version: 2
  build:
    jobs:
      - build-mac
