version: 2.1

jobs:
  build-mac:
    macos:
      xcode: 13.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - visual-studio-mac-v2
      - run:
          name: Install Visual Studio for Mac (if necessary)
          command: |
            if [ ! -d "/Applications/Visual Studio.app" -o \
                 ! -d "/Applications/Xamarin Profiler.app" -o \
                 ! -d "/Library/Frameworks/Mono.framework" -o \
                 ! -d "/Library/Frameworks/Xamarin.Mac.framework" -o \
                 ! -d "/usr/local/share/dotnet" \
            ]; then
              export HOMEBREW_NO_AUTO_UPDATE=1
              brew tap homebrew/cask-versions
              brew install visual-studio jq
              ./.circleci/install-vs-mac.sh
            fi
      - save_cache:
          key: visual-studio-mac-v2
          paths:
            - /Applications/Visual Studio.app
            - /Applications/Xamarin Profiler.app
            - /Library/Frameworks/Mono.framework
            - /Library/Frameworks/Xamarin.Mac.framework
            - /usr/local/share/dotnet
            - /etc/paths.d/dotnet
            - /etc/paths.d/dotnet-cli-tools
            - /etc/paths.d/mono-commands
      - run:
          name: Restore NuGet dependencies
          command: msbuild -t:Restore -p:Configuration=Release scratch-link.sln
      - run:
          name: Build for Mac
          command: |
            "/Applications/Visual Studio.app/Contents/MacOS/vstool" build -t:Build -c:Release "${PWD}/scratch-link.sln"
      - run:
          name: Zip the app
          command: |
            mkdir -p Artifacts
            cd scratch-link/bin/Debug/net6.0-maccatalyst/*/*.app/..
            ditto -v -c -k --sequesterRsrc --keepParent --zlibCompressionLevel 9 \
              scratch-link.app ../../../../../Artifacts/scratch-link-mac.zip
      - store_artifacts:
          path: Artifacts/
workflows:
  version: 2
  build:
    jobs:
      - build-mac
